services:
  php:
    container_name: php-con
    build:
      context: .
      dockerfile: Dockerfile
    image: jdel-php-apache
    volumes:
      - ./src:/var/www/html/
    environment:
      XDEBUG_MODE: debug,developer
      XDEBUG_CONFIG: remote_enable=1 remote_autostart=1
    ports:
      - 80:80
    networks:
      - app-network

  mysql:
    container_name: mysql-con
    image: mysql
    # command: --innodb-force-recovery=6 // when I had an issue #ib_redo0 not empty
    volumes:
      - ./database:/var/lib/mysql
      - ./script_DB:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: LeGrenierDuJoueur_DB
      MYSQL_USER: jdelobel
      MYSQL_PASSWORD: password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin-con
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql-con
      PMA_USER: jdelobel
      PMA_PASSWORD: password
    ports:
      - '8080:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge